config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :games
  resources :users, only: [:show]
  
  root "games#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    validates :home_team, :presence => true
    validates :away_team, :presence => true
    validates :rate_team, :presence => true
    
    has_many :rates
    belongs_to :user, optional: true
    
    accepts_nested_attributes_for :rates, allow_destroy: true
end

app/models/rate.rb
class Rate < ApplicationRecord
    validates :name, :presence => true
    belongs_to :game, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :games
  validates :nickname, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /games
  def index
    @games = Game.order('id DESC')
  end

  # GET /games/1 
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
    16.times{ @game.rates.build }
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to action: :index
    else
      render "new"
    end
    
  end

  # PATCH/PUT /games/1 
  def update
    if @game.user_id == current_user.id
      @game.update(game_params)
    end
    redirect_to action: :index
  end

  # DELETE /games/1
  def destroy
    if @game.user_id == current_user.id
      @game.destroy
    end
    redirect_to action: :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end
    
    def game_params
      params.require(:game).permit(:home_team, :away_team, :home_score, :away_score, :date, :mom, :game_text, :rate_team, rates_attributes: [:game_id, :position, :name, :rate, :rate_text, :id, :_destroy]).merge(user_id: current_user.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @games = Game.where(user_id: current_user.id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |form| %>
  <%= render 'layouts/error_messages', model: form.object %>

  <div class="wrap">
    <h2>Game Information</h2>
  </div>

  <div class="game-info-form">
    
    <div class="game-form-box">
      <div class="label">Match</div> 
      <%= form.text_field :home_team, :placeholder => "Home Team" %>
      <div class="colon">:</div>
      <%= form.text_field :away_team, :placeholder => "Away Team" %>
    </div>

    <div class="game-form-box">
      <div class="label">Score</div>
      <%= form.number_field :home_score, min: 0, :placeholder => "Home Score" %>
      <div class="colon">:</div>
      <%= form.number_field :away_score, min: 0, :placeholder => "Away Score" %>
    </div>

    <div class="game-form-box">
      <div class="label">Date</div>
      <%= form.date_select :date %>
    </div>

    <div class="game-form-box">
      <div class="label">MOTM</div> 
      <%= form.text_field :mom, :placeholder => "Man of the Match" %>
    </div>

    <div class="game-form-box">
      <div class="label">Game Comment</div> 
      <%= form.text_area :game_text, size: "100x15", :placeholder => "Game Comment" %>
    </div>

    <div class="game-form-box">
      <div class="label">Rate Team</div> 
      <%= form.text_field :rate_team, :placeholder => "Rate Team"%>
    </div>
    
  </div>
  
  <div class="wrap">
    <h2>Player Rate</h2>
  </div>
  
    <div class="rate-form">
      <%= form.fields_for :rates do |r| %>
        <%= render partial: "rate_fields", locals: {f: r} %>
      <% end %>
    </div>  

    <div class="wrap">
      <%= form.submit 'RATE', class: "btn btn-submit" %>
    </div>
<% end %>

app/views/games/_game.html.erb
<div class="content">
        
    <div class="info-box">
    
        <p class="team-name"><a href="/games/<%= game.id %>"><%= game.home_team %> <%= game.home_score %> : <%= game.away_score %> <%= game.away_team %></a></p>
    
        <p class="info"><strong>MATCH DATE</strong>: <%= game.date %></p>
        <p class="info"><strong>RATED TEAM</strong>: <%= game.rate_team %></p>
        <p class="info"><strong>RATED BY</strong>: <%= game.user.nickname %></p>
            
        <ul class="links">
            <li class="action-option"><%= link_to "SHOW", game_path(game), method: :get, class: "btn" %></li>
            <% if user_signed_in? && game.user_id == current_user.id %>  
                <li class="action-option"><%= link_to 'EDIT', edit_game_path(game), method: :get, class: "btn" %></li>
                <li class="action-option"><%= link_to 'DELETE', "/games/#{game.id}", method: :delete, class: "btn", data: {confirm: "削除しますか？"} %></li>
            <% end %>
        </ul>
            
    </div>
    
</div>

app/views/games/_rate_fields.html.erb
<div class="nested-fields">
    <div class="rate-box">
        <div class="player-form-box">
            <div class="label">Position</div> 
            <%= f.select :position, {'GK': 'GK', 'CB': 'CB', 'RB': 'RB', 'LB': 'LB', 'DMF': 'DMF', 'CMF': 'CMF', 'OMF': 'OMF', 'RMF': 'RMF', 'LMF': 'LMF', 'RWG': 'RWG', 'LWG': 'LWG', 'ST': 'ST', 'CF': 'CF' }, { include_blank: 'SELECT' } %>
        </div>
    
        <div class="player-form-box">
            <div class="label">Name</div> 
            <%= f.text_field :name, :placeholder => "Player Name" %>
        </div> 
    
        <div class="player-form-box">
            <div class="label">Rate</div> 
            <%= f.select :rate, {'0': '0', '1': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9, '10': 10}, { include_blank: 'RATE'} %>
        </div>
    
        <div class="player-form-box">
            <div class="label">Player Comment</div> 
            <%= f.text_area :rate_text, size: "50x5", :placeholder => "Player Comment" %>
        </div>

        <div class="remove">  
            <%= link_to_remove_association "remove", f, class: 'btn' %>
        </div>

    </div>
</div>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game, class: "btn" %> |
<%= link_to 'Back', games_path, class: "btn" %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rates</h1>

<div id="wrap" class="content">
<% @games.each do |game| %>
<%= render 'game', game: game %>
<% end %>
</div>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

 <%= link_to 'Back', games_path, class: "btn" %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @game.home_team %> vs <%= @game.away_team %></h1>

<div class="wrap">
  <h2>Match Information</h2>
</div>

  <ul class="match-info">
    <li><strong>MATCH DATE</strong>: <%= @game.date %></li>
    <li><strong>SCORE</strong>: <%= @game.home_team %> <%= @game.home_score %> : <%= @game.away_score %> <%= @game.away_team%></li>
    <li><strong>MOTM</strong>: <%= @game.mom %></li>
    <li class="game-comment"><strong>COMMENT</strong>: <%= @game.game_text %></li>
  </ul>
  
<div class="wrap">
  <h2><%= @game.rate_team %>'s Player Rate</h2>
</div>

  <% @game.rates.each do |rate| %>
    <div class="player-rate">
      <div class="rate-box">
        <p><strong><%= rate.position %> - <%= rate.name %></strong></p>
        <p><strong>RATE</strong>: <%= rate.rate %></p>
        <p class="player-comment"><strong>COMMENT</strong>: <%= rate.rate_text %></p>
      </div>
    </div>  
  <% end %>

<% if user_signed_in? && @game.user_id == current_user.id %>
<%= link_to 'Edit', edit_game_path(@game), class: "btn" %> | 
<% end %>
<%= link_to 'Back', games_path, class: "btn" %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <% model.errors.full_messages.each do |message| %>
    <div class="alert alert-danger"><%= message %></div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ratethegame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="header">
      <div class="header__bar">
        <a href="/" class="logo">RateTheGame</a>
        <% if user_signed_in? %>  
          <ul class="bar">
            <li class="header_option"><%= link_to "RATE", new_game_path, class: "option" %></li>
            <li class="header_option "><%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class: "option" %></li>
            <li class="header_option"><%= link_to "MY PAGE", "/users/:#{current_user.id}", class: "option" %></li>
          </ul>
        <% else %>
          <ul class="bar">
            <li class="header_option"><%= link_to "LOG IN", new_user_session_path, class: "option" %></li>
            <li class="header_option"><%= link_to "CREATE ACCOUNT", new_user_registration_path, class: "option" %></li>
          </ul>
        <% end %>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1>My Page</h1>

<% @games.each do |game| %>
<%= render 'games/game', game: game %>
<% end %>